twig:
    default_path: '%kernel.project_dir%/templates'

    paths:
        '%kernel.project_dir%/public/picture': images
        '%kernel.project_dir%/public/css': styles

when@test:
    twig:
        strict_variables: true